;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Interactable.Ingredient.MushroomIngredient",NewTagName="Interactable.Ingredient.Mushroom")
+GameplayTagList=(Tag="Frog.Interacting",DevComment="")
+GameplayTagList=(Tag="Interactable.Bottle",DevComment="")
+GameplayTagList=(Tag="Interactable.Cauldron",DevComment="")
+GameplayTagList=(Tag="Interactable.Ingredient",DevComment="")
+GameplayTagList=(Tag="Interactable.Ingredient.Mushroom",DevComment="")
+GameplayTagList=(Tag="Interactable.Ingredient.Mushroom.Cooked",DevComment="")
+GameplayTagList=(Tag="Interactable.Ingredient.Mushroom.Raw",DevComment="")
+GameplayTagList=(Tag="Interactable.OrderCounter",DevComment="")
+GameplayTagList=(Tag="Interactable.Player",DevComment="")
+GameplayTagList=(Tag="Interactable.Spawner.Bottle",DevComment="")
+GameplayTagList=(Tag="Interactable.Spawner.Mushroom",DevComment="")
+GameplayTagList=(Tag="Interactable.TrashCan",DevComment="")

