;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Frog.AbilitySlot.Dive",DevComment="")
+GameplayTagList=(Tag="Frog.AbilitySlot.Grapple",DevComment="")
+GameplayTagList=(Tag="Frog.AbilitySlot.Jump",DevComment="")
+GameplayTagList=(Tag="Frog.AbilitySlot.Primary",DevComment="")
+GameplayTagList=(Tag="Frog.AbilitySlot.Utility",DevComment="")
+GameplayTagList=(Tag="Frog.Cooldown",DevComment="")
+GameplayTagList=(Tag="Frog.Cooldown.Grapple",DevComment="")
+GameplayTagList=(Tag="Frog.Cooldown.Jump",DevComment="")
+GameplayTagList=(Tag="Frog.Cooldown.Primary",DevComment="")
+GameplayTagList=(Tag="Frog.Cooldown.Secondary",DevComment="")
+GameplayTagList=(Tag="Frog.Cooldown.Utility",DevComment="")
+GameplayTagList=(Tag="Frog.State.Downed",DevComment="")

