;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=True
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Interactable.Ingredient.MushroomIngredient",NewTagName="Interactable.Ingredient.Mushroom")
+GameplayTagList=(Tag="Frog.Interacting",DevComment="")
+GameplayTagList=(Tag="Interactable.Consumer.OrderCounter",DevComment="")
+GameplayTagList=(Tag="Interactable.Consumer.TrashCan",DevComment="")
+GameplayTagList=(Tag="Interactable.Container.Bottle",DevComment="")
+GameplayTagList=(Tag="Interactable.Liquid",DevComment="")
+GameplayTagList=(Tag="Interactable.Process.Cauldron",DevComment="")
+GameplayTagList=(Tag="Interactable.Solid",DevComment="")
+GameplayTagList=(Tag="Interactable.Solid.Mushroom.Cooked",DevComment="")
+GameplayTagList=(Tag="Interactable.Solid.Mushroom.Raw",DevComment="")
+GameplayTagList=(Tag="Interactable.Spawner.Bottle",DevComment="")
+GameplayTagList=(Tag="Interactable.Spawner.Mushroom",DevComment="")

